pipeline{
    agent any

    tools{
        maven "jenkins-maven"
    }

    stages{
        stage("Build"){
            steps{
               echo "Building the app !"
            }
        }
    }
}
